CREATE TABLE USER (
  ID          INT(6)       NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  USERNAME    VARCHAR(36)  NOT NULL,
  PASSWORD    VARCHAR(100) NOT NULL,
  ROLE        VARCHAR(10)  NOT NULL,
  TOKEN       VARCHAR(200) NOT NULL,
  CREATE_DATE DATETIME     NOT NULL
);