CREATE TABLE BOOK (
  ID           INT(6)       NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  NAME         VARCHAR(200) NOT NULL,
  AUTHOR       VARCHAR(100) NOT NULL,
  IS_AVAILABLE INT(1)       NOT NULL DEFAULT 1
);