CREATE TABLE ORDERS (
  ID          INT(6)    NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  USER_ID     INT(6)    NOT NULL,
  BOOK_ID     INT(6)    NOT NULL,
  CREATE_DATE DATETIME  NOT NULL,
  RETURN_DATE DATETIME,
  FOREIGN KEY (USER_ID) REFERENCES USER (ID),
  FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);